on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@60f9666828d33cc321ea5a5c02042d940f790682 # v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run linter
        run: uv run ruff check
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - name: Run actionlint
        uses: reviewdog/action-actionlint@50842263c20a7c46bd0065b9e624d3c569db061e # v1

  zizmor:
    name: zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@60f9666828d33cc321ea5a5c02042d940f790682 # v6
      - name: Run zizmor
        run: uvx zizmor --format sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@4187e74d05793876e9989daffde9c3e66b4acd07 # v3
        with:
          sarif_file: results.sarif
          category: zizmor
